# Site settings
title: Jessi Jullie
description: >
  A simple, minimal Jekyll theme for a personal web page and blog, focusing on white space and readability

baseurl: "/Jessi" # the subpath of your site, e.g. /blog/

the base hostname & protocol for your site
url: "http://jessijullie.me"

author: Jessi
fullname: JessiJullie
github: https://github.com/JessiJullie
linkedin: https://www.linkedin.com/in/jessijullie/
email: jessi.jullie@gmail.com


# Syntax highlighting
highlightstyle: 'agate'
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

 variables:
 JEKYLL_ENV: production

# Exclude
#exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/

# Build settings
highlighter: null
markdown: kramdown

kramdown:
parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
future: true

# This will require each of these plugins automatically.
